// Code generated by "stringer -type=Condition"; DO NOT EDIT.

package decode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConditionNone-0]
	_ = x[ConditionZero-1]
	_ = x[ConditionNotZero-2]
	_ = x[ConditionCarry-3]
	_ = x[ConditionNotCarry-4]
}

const _Condition_name = "ConditionNoneConditionZeroConditionNotZeroConditionCarryConditionNotCarry"

var _Condition_index = [...]uint8{0, 13, 26, 42, 56, 73}

func (i Condition) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Condition_index)-1 {
		return "Condition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Condition_name[_Condition_index[idx]:_Condition_index[idx+1]]
}
