// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package decode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOP-0]
	_ = x[PREFIX-1]
	_ = x[STOP-2]
	_ = x[HALT-3]
	_ = x[DI-4]
	_ = x[EI-5]
	_ = x[DAA-6]
	_ = x[SCF-7]
	_ = x[CPL-8]
	_ = x[CCF-9]
	_ = x[JR_CC_S8-10]
	_ = x[JP_CC_A16-11]
	_ = x[JP_HL-12]
	_ = x[ADD_SP_S8-13]
	_ = x[PUSH_R16-14]
	_ = x[CALL_CC_A16-15]
	_ = x[RST-16]
	_ = x[POP_R16-17]
	_ = x[RET_CC-18]
	_ = x[RETI-19]
	_ = x[INC_R8-20]
	_ = x[DEC_R8-21]
	_ = x[ADD_R8-22]
	_ = x[ADC_R8-23]
	_ = x[SUB_R8-24]
	_ = x[SBC_R8-25]
	_ = x[AND_R8-26]
	_ = x[XOR_R8-27]
	_ = x[OR_R8-28]
	_ = x[CP_R8-29]
	_ = x[INC_R16-30]
	_ = x[DEC_R16-31]
	_ = x[ADD_HL_R16-32]
	_ = x[RLCA-33]
	_ = x[RLA-34]
	_ = x[RRCA-35]
	_ = x[RRA-36]
	_ = x[ADD_D8-37]
	_ = x[SUB_D8-38]
	_ = x[AND_D8-39]
	_ = x[OR_D8-40]
	_ = x[ADC_D8-41]
	_ = x[SBC_D8-42]
	_ = x[XOR_D8-43]
	_ = x[CP_D8-44]
	_ = x[LD_R8_R8-45]
	_ = x[LD_R8_D8-46]
	_ = x[LD_A8_A-47]
	_ = x[LD_A_A8-48]
	_ = x[LD_CP_A-49]
	_ = x[LD_A_CP-50]
	_ = x[LD_A16_A-51]
	_ = x[LD_A_A16-52]
	_ = x[LD_R16_D16-53]
	_ = x[LD_R16P_A-54]
	_ = x[LD_HLPI_A-55]
	_ = x[LD_HLPD_A-56]
	_ = x[LD_A_R16P-57]
	_ = x[LD_A_HLPI-58]
	_ = x[LD_A_HLPD-59]
	_ = x[LD_A16_SP-60]
	_ = x[LD_HL_SP_S8-61]
	_ = x[LD_SP_HL-62]
}

const _Opcode_name = "NOPPREFIXSTOPHALTDIEIDAASCFCPLCCFJR_CC_S8JP_CC_A16JP_HLADD_SP_S8PUSH_R16CALL_CC_A16RSTPOP_R16RET_CCRETIINC_R8DEC_R8ADD_R8ADC_R8SUB_R8SBC_R8AND_R8XOR_R8OR_R8CP_R8INC_R16DEC_R16ADD_HL_R16RLCARLARRCARRAADD_D8SUB_D8AND_D8OR_D8ADC_D8SBC_D8XOR_D8CP_D8LD_R8_R8LD_R8_D8LD_A8_ALD_A_A8LD_CP_ALD_A_CPLD_A16_ALD_A_A16LD_R16_D16LD_R16P_ALD_HLPI_ALD_HLPD_ALD_A_R16PLD_A_HLPILD_A_HLPDLD_A16_SPLD_HL_SP_S8LD_SP_HL"

var _Opcode_index = [...]uint16{0, 3, 9, 13, 17, 19, 21, 24, 27, 30, 33, 41, 50, 55, 64, 72, 83, 86, 93, 99, 103, 109, 115, 121, 127, 133, 139, 145, 151, 156, 161, 168, 175, 185, 189, 192, 196, 199, 205, 211, 217, 222, 228, 234, 240, 245, 253, 261, 268, 275, 282, 289, 297, 305, 315, 324, 333, 342, 351, 360, 369, 378, 389, 397}

func (i Opcode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Opcode_index)-1 {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[idx]:_Opcode_index[idx+1]]
}
