// Code generated by "stringer -type PrefixOpcode"; DO NOT EDIT.

package decode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RLC-0]
	_ = x[RRC-1]
	_ = x[RL-2]
	_ = x[RR-3]
	_ = x[SLA-4]
	_ = x[SRA-5]
	_ = x[SWAP-6]
	_ = x[SRL-7]
	_ = x[BIT-8]
	_ = x[RES-9]
	_ = x[SET-10]
}

const _PrefixOpcode_name = "RLCRRCRLRRSLASRASWAPSRLBITRESSET"

var _PrefixOpcode_index = [...]uint8{0, 3, 6, 8, 10, 13, 16, 20, 23, 26, 29, 32}

func (i PrefixOpcode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PrefixOpcode_index)-1 {
		return "PrefixOpcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrefixOpcode_name[_PrefixOpcode_index[idx]:_PrefixOpcode_index[idx+1]]
}
