package decode

import "testing"

var allPrefixInstructions = map[uint8]PrefixInstruction{
	0x00: {Opcode: RLC, Operand: RegisterB},
	0x01: {Opcode: RLC, Operand: RegisterC},
	0x02: {Opcode: RLC, Operand: RegisterD},
	0x03: {Opcode: RLC, Operand: RegisterE},
	0x04: {Opcode: RLC, Operand: RegisterH},
	0x05: {Opcode: RLC, Operand: RegisterL},
	0x06: {Opcode: RLC, Operand: RegisterHLP},
	0x07: {Opcode: RLC, Operand: RegisterA},

	0x08: {Opcode: RRC, Operand: RegisterB},
	0x09: {Opcode: RRC, Operand: RegisterC},
	0x0A: {Opcode: RRC, Operand: RegisterD},
	0x0B: {Opcode: RRC, Operand: RegisterE},
	0x0C: {Opcode: RRC, Operand: RegisterH},
	0x0D: {Opcode: RRC, Operand: RegisterL},
	0x0E: {Opcode: RRC, Operand: RegisterHLP},
	0x0F: {Opcode: RRC, Operand: RegisterA},

	0x10: {Opcode: RL, Operand: RegisterB},
	0x11: {Opcode: RL, Operand: RegisterC},
	0x12: {Opcode: RL, Operand: RegisterD},
	0x13: {Opcode: RL, Operand: RegisterE},
	0x14: {Opcode: RL, Operand: RegisterH},
	0x15: {Opcode: RL, Operand: RegisterL},
	0x16: {Opcode: RL, Operand: RegisterHLP},
	0x17: {Opcode: RL, Operand: RegisterA},

	0x18: {Opcode: RR, Operand: RegisterB},
	0x19: {Opcode: RR, Operand: RegisterC},
	0x1A: {Opcode: RR, Operand: RegisterD},
	0x1B: {Opcode: RR, Operand: RegisterE},
	0x1C: {Opcode: RR, Operand: RegisterH},
	0x1D: {Opcode: RR, Operand: RegisterL},
	0x1E: {Opcode: RR, Operand: RegisterHLP},
	0x1F: {Opcode: RR, Operand: RegisterA},

	0x20: {Opcode: SLA, Operand: RegisterB},
	0x21: {Opcode: SLA, Operand: RegisterC},
	0x22: {Opcode: SLA, Operand: RegisterD},
	0x23: {Opcode: SLA, Operand: RegisterE},
	0x24: {Opcode: SLA, Operand: RegisterH},
	0x25: {Opcode: SLA, Operand: RegisterL},
	0x26: {Opcode: SLA, Operand: RegisterHLP},
	0x27: {Opcode: SLA, Operand: RegisterA},

	0x28: {Opcode: SRA, Operand: RegisterB},
	0x29: {Opcode: SRA, Operand: RegisterC},
	0x2A: {Opcode: SRA, Operand: RegisterD},
	0x2B: {Opcode: SRA, Operand: RegisterE},
	0x2C: {Opcode: SRA, Operand: RegisterH},
	0x2D: {Opcode: SRA, Operand: RegisterL},
	0x2E: {Opcode: SRA, Operand: RegisterHLP},
	0x2F: {Opcode: SRA, Operand: RegisterA},

	0x30: {Opcode: SWAP, Operand: RegisterB},
	0x31: {Opcode: SWAP, Operand: RegisterC},
	0x32: {Opcode: SWAP, Operand: RegisterD},
	0x33: {Opcode: SWAP, Operand: RegisterE},
	0x34: {Opcode: SWAP, Operand: RegisterH},
	0x35: {Opcode: SWAP, Operand: RegisterL},
	0x36: {Opcode: SWAP, Operand: RegisterHLP},
	0x37: {Opcode: SWAP, Operand: RegisterA},

	0x38: {Opcode: SRL, Operand: RegisterB},
	0x39: {Opcode: SRL, Operand: RegisterC},
	0x3A: {Opcode: SRL, Operand: RegisterD},
	0x3B: {Opcode: SRL, Operand: RegisterE},
	0x3C: {Opcode: SRL, Operand: RegisterH},
	0x3D: {Opcode: SRL, Operand: RegisterL},
	0x3E: {Opcode: SRL, Operand: RegisterHLP},
	0x3F: {Opcode: SRL, Operand: RegisterA},

	0x40: {Opcode: BIT, Operand: RegisterB, Bit: 0},
	0x41: {Opcode: BIT, Operand: RegisterC, Bit: 0},
	0x42: {Opcode: BIT, Operand: RegisterD, Bit: 0},
	0x43: {Opcode: BIT, Operand: RegisterE, Bit: 0},
	0x44: {Opcode: BIT, Operand: RegisterH, Bit: 0},
	0x45: {Opcode: BIT, Operand: RegisterL, Bit: 0},
	0x46: {Opcode: BIT, Operand: RegisterHLP, Bit: 0},
	0x47: {Opcode: BIT, Operand: RegisterA, Bit: 0},
	0x48: {Opcode: BIT, Operand: RegisterB, Bit: 1},
	0x49: {Opcode: BIT, Operand: RegisterC, Bit: 1},
	0x4A: {Opcode: BIT, Operand: RegisterD, Bit: 1},
	0x4B: {Opcode: BIT, Operand: RegisterE, Bit: 1},
	0x4C: {Opcode: BIT, Operand: RegisterH, Bit: 1},
	0x4D: {Opcode: BIT, Operand: RegisterL, Bit: 1},
	0x4E: {Opcode: BIT, Operand: RegisterHLP, Bit: 1},
	0x4F: {Opcode: BIT, Operand: RegisterA, Bit: 1},
	0x50: {Opcode: BIT, Operand: RegisterB, Bit: 2},
	0x51: {Opcode: BIT, Operand: RegisterC, Bit: 2},
	0x52: {Opcode: BIT, Operand: RegisterD, Bit: 2},
	0x53: {Opcode: BIT, Operand: RegisterE, Bit: 2},
	0x54: {Opcode: BIT, Operand: RegisterH, Bit: 2},
	0x55: {Opcode: BIT, Operand: RegisterL, Bit: 2},
	0x56: {Opcode: BIT, Operand: RegisterHLP, Bit: 2},
	0x57: {Opcode: BIT, Operand: RegisterA, Bit: 2},
	0x58: {Opcode: BIT, Operand: RegisterB, Bit: 3},
	0x59: {Opcode: BIT, Operand: RegisterC, Bit: 3},
	0x5A: {Opcode: BIT, Operand: RegisterD, Bit: 3},
	0x5B: {Opcode: BIT, Operand: RegisterE, Bit: 3},
	0x5C: {Opcode: BIT, Operand: RegisterH, Bit: 3},
	0x5D: {Opcode: BIT, Operand: RegisterL, Bit: 3},
	0x5E: {Opcode: BIT, Operand: RegisterHLP, Bit: 3},
	0x5F: {Opcode: BIT, Operand: RegisterA, Bit: 3},
	0x60: {Opcode: BIT, Operand: RegisterB, Bit: 4},
	0x61: {Opcode: BIT, Operand: RegisterC, Bit: 4},
	0x62: {Opcode: BIT, Operand: RegisterD, Bit: 4},
	0x63: {Opcode: BIT, Operand: RegisterE, Bit: 4},
	0x64: {Opcode: BIT, Operand: RegisterH, Bit: 4},
	0x65: {Opcode: BIT, Operand: RegisterL, Bit: 4},
	0x66: {Opcode: BIT, Operand: RegisterHLP, Bit: 4},
	0x67: {Opcode: BIT, Operand: RegisterA, Bit: 4},
	0x68: {Opcode: BIT, Operand: RegisterB, Bit: 5},
	0x69: {Opcode: BIT, Operand: RegisterC, Bit: 5},
	0x6A: {Opcode: BIT, Operand: RegisterD, Bit: 5},
	0x6B: {Opcode: BIT, Operand: RegisterE, Bit: 5},
	0x6C: {Opcode: BIT, Operand: RegisterH, Bit: 5},
	0x6D: {Opcode: BIT, Operand: RegisterL, Bit: 5},
	0x6E: {Opcode: BIT, Operand: RegisterHLP, Bit: 5},
	0x6F: {Opcode: BIT, Operand: RegisterA, Bit: 5},
	0x70: {Opcode: BIT, Operand: RegisterB, Bit: 6},
	0x71: {Opcode: BIT, Operand: RegisterC, Bit: 6},
	0x72: {Opcode: BIT, Operand: RegisterD, Bit: 6},
	0x73: {Opcode: BIT, Operand: RegisterE, Bit: 6},
	0x74: {Opcode: BIT, Operand: RegisterH, Bit: 6},
	0x75: {Opcode: BIT, Operand: RegisterL, Bit: 6},
	0x76: {Opcode: BIT, Operand: RegisterHLP, Bit: 6},
	0x77: {Opcode: BIT, Operand: RegisterA, Bit: 6},
	0x78: {Opcode: BIT, Operand: RegisterB, Bit: 7},
	0x79: {Opcode: BIT, Operand: RegisterC, Bit: 7},
	0x7A: {Opcode: BIT, Operand: RegisterD, Bit: 7},
	0x7B: {Opcode: BIT, Operand: RegisterE, Bit: 7},
	0x7C: {Opcode: BIT, Operand: RegisterH, Bit: 7},
	0x7D: {Opcode: BIT, Operand: RegisterL, Bit: 7},
	0x7E: {Opcode: BIT, Operand: RegisterHLP, Bit: 7},
	0x7F: {Opcode: BIT, Operand: RegisterA, Bit: 7},

	0x80: {Opcode: RES, Operand: RegisterB, Bit: 0},
	0x81: {Opcode: RES, Operand: RegisterC, Bit: 0},
	0x82: {Opcode: RES, Operand: RegisterD, Bit: 0},
	0x83: {Opcode: RES, Operand: RegisterE, Bit: 0},
	0x84: {Opcode: RES, Operand: RegisterH, Bit: 0},
	0x85: {Opcode: RES, Operand: RegisterL, Bit: 0},
	0x86: {Opcode: RES, Operand: RegisterHLP, Bit: 0},
	0x87: {Opcode: RES, Operand: RegisterA, Bit: 0},
	0x88: {Opcode: RES, Operand: RegisterB, Bit: 1},
	0x89: {Opcode: RES, Operand: RegisterC, Bit: 1},
	0x8A: {Opcode: RES, Operand: RegisterD, Bit: 1},
	0x8B: {Opcode: RES, Operand: RegisterE, Bit: 1},
	0x8C: {Opcode: RES, Operand: RegisterH, Bit: 1},
	0x8D: {Opcode: RES, Operand: RegisterL, Bit: 1},
	0x8E: {Opcode: RES, Operand: RegisterHLP, Bit: 1},
	0x8F: {Opcode: RES, Operand: RegisterA, Bit: 1},
	0x90: {Opcode: RES, Operand: RegisterB, Bit: 2},
	0x91: {Opcode: RES, Operand: RegisterC, Bit: 2},
	0x92: {Opcode: RES, Operand: RegisterD, Bit: 2},
	0x93: {Opcode: RES, Operand: RegisterE, Bit: 2},
	0x94: {Opcode: RES, Operand: RegisterH, Bit: 2},
	0x95: {Opcode: RES, Operand: RegisterL, Bit: 2},
	0x96: {Opcode: RES, Operand: RegisterHLP, Bit: 2},
	0x97: {Opcode: RES, Operand: RegisterA, Bit: 2},
	0x98: {Opcode: RES, Operand: RegisterB, Bit: 3},
	0x99: {Opcode: RES, Operand: RegisterC, Bit: 3},
	0x9A: {Opcode: RES, Operand: RegisterD, Bit: 3},
	0x9B: {Opcode: RES, Operand: RegisterE, Bit: 3},
	0x9C: {Opcode: RES, Operand: RegisterH, Bit: 3},
	0x9D: {Opcode: RES, Operand: RegisterL, Bit: 3},
	0x9E: {Opcode: RES, Operand: RegisterHLP, Bit: 3},
	0x9F: {Opcode: RES, Operand: RegisterA, Bit: 3},
	0xA0: {Opcode: RES, Operand: RegisterB, Bit: 4},
	0xA1: {Opcode: RES, Operand: RegisterC, Bit: 4},
	0xA2: {Opcode: RES, Operand: RegisterD, Bit: 4},
	0xA3: {Opcode: RES, Operand: RegisterE, Bit: 4},
	0xA4: {Opcode: RES, Operand: RegisterH, Bit: 4},
	0xA5: {Opcode: RES, Operand: RegisterL, Bit: 4},
	0xA6: {Opcode: RES, Operand: RegisterHLP, Bit: 4},
	0xA7: {Opcode: RES, Operand: RegisterA, Bit: 4},
	0xA8: {Opcode: RES, Operand: RegisterB, Bit: 5},
	0xA9: {Opcode: RES, Operand: RegisterC, Bit: 5},
	0xAA: {Opcode: RES, Operand: RegisterD, Bit: 5},
	0xAB: {Opcode: RES, Operand: RegisterE, Bit: 5},
	0xAC: {Opcode: RES, Operand: RegisterH, Bit: 5},
	0xAD: {Opcode: RES, Operand: RegisterL, Bit: 5},
	0xAE: {Opcode: RES, Operand: RegisterHLP, Bit: 5},
	0xAF: {Opcode: RES, Operand: RegisterA, Bit: 5},
	0xB0: {Opcode: RES, Operand: RegisterB, Bit: 6},
	0xB1: {Opcode: RES, Operand: RegisterC, Bit: 6},
	0xB2: {Opcode: RES, Operand: RegisterD, Bit: 6},
	0xB3: {Opcode: RES, Operand: RegisterE, Bit: 6},
	0xB4: {Opcode: RES, Operand: RegisterH, Bit: 6},
	0xB5: {Opcode: RES, Operand: RegisterL, Bit: 6},
	0xB6: {Opcode: RES, Operand: RegisterHLP, Bit: 6},
	0xB7: {Opcode: RES, Operand: RegisterA, Bit: 6},
	0xB8: {Opcode: RES, Operand: RegisterB, Bit: 7},
	0xB9: {Opcode: RES, Operand: RegisterC, Bit: 7},
	0xBA: {Opcode: RES, Operand: RegisterD, Bit: 7},
	0xBB: {Opcode: RES, Operand: RegisterE, Bit: 7},
	0xBC: {Opcode: RES, Operand: RegisterH, Bit: 7},
	0xBD: {Opcode: RES, Operand: RegisterL, Bit: 7},
	0xBE: {Opcode: RES, Operand: RegisterHLP, Bit: 7},
	0xBF: {Opcode: RES, Operand: RegisterA, Bit: 7},

	0xC0: {Opcode: SET, Operand: RegisterB, Bit: 0},
	0xC1: {Opcode: SET, Operand: RegisterC, Bit: 0},
	0xC2: {Opcode: SET, Operand: RegisterD, Bit: 0},
	0xC3: {Opcode: SET, Operand: RegisterE, Bit: 0},
	0xC4: {Opcode: SET, Operand: RegisterH, Bit: 0},
	0xC5: {Opcode: SET, Operand: RegisterL, Bit: 0},
	0xC6: {Opcode: SET, Operand: RegisterHLP, Bit: 0},
	0xC7: {Opcode: SET, Operand: RegisterA, Bit: 0},
	0xC8: {Opcode: SET, Operand: RegisterB, Bit: 1},
	0xC9: {Opcode: SET, Operand: RegisterC, Bit: 1},
	0xCA: {Opcode: SET, Operand: RegisterD, Bit: 1},
	0xCB: {Opcode: SET, Operand: RegisterE, Bit: 1},
	0xCC: {Opcode: SET, Operand: RegisterH, Bit: 1},
	0xCD: {Opcode: SET, Operand: RegisterL, Bit: 1},
	0xCE: {Opcode: SET, Operand: RegisterHLP, Bit: 1},
	0xCF: {Opcode: SET, Operand: RegisterA, Bit: 1},
	0xD0: {Opcode: SET, Operand: RegisterB, Bit: 2},
	0xD1: {Opcode: SET, Operand: RegisterC, Bit: 2},
	0xD2: {Opcode: SET, Operand: RegisterD, Bit: 2},
	0xD3: {Opcode: SET, Operand: RegisterE, Bit: 2},
	0xD4: {Opcode: SET, Operand: RegisterH, Bit: 2},
	0xD5: {Opcode: SET, Operand: RegisterL, Bit: 2},
	0xD6: {Opcode: SET, Operand: RegisterHLP, Bit: 2},
	0xD7: {Opcode: SET, Operand: RegisterA, Bit: 2},
	0xD8: {Opcode: SET, Operand: RegisterB, Bit: 3},
	0xD9: {Opcode: SET, Operand: RegisterC, Bit: 3},
	0xDA: {Opcode: SET, Operand: RegisterD, Bit: 3},
	0xDB: {Opcode: SET, Operand: RegisterE, Bit: 3},
	0xDC: {Opcode: SET, Operand: RegisterH, Bit: 3},
	0xDD: {Opcode: SET, Operand: RegisterL, Bit: 3},
	0xDE: {Opcode: SET, Operand: RegisterHLP, Bit: 3},
	0xDF: {Opcode: SET, Operand: RegisterA, Bit: 3},
	0xE0: {Opcode: SET, Operand: RegisterB, Bit: 4},
	0xE1: {Opcode: SET, Operand: RegisterC, Bit: 4},
	0xE2: {Opcode: SET, Operand: RegisterD, Bit: 4},
	0xE3: {Opcode: SET, Operand: RegisterE, Bit: 4},
	0xE4: {Opcode: SET, Operand: RegisterH, Bit: 4},
	0xE5: {Opcode: SET, Operand: RegisterL, Bit: 4},
	0xE6: {Opcode: SET, Operand: RegisterHLP, Bit: 4},
	0xE7: {Opcode: SET, Operand: RegisterA, Bit: 4},
	0xE8: {Opcode: SET, Operand: RegisterB, Bit: 5},
	0xE9: {Opcode: SET, Operand: RegisterC, Bit: 5},
	0xEA: {Opcode: SET, Operand: RegisterD, Bit: 5},
	0xEB: {Opcode: SET, Operand: RegisterE, Bit: 5},
	0xEC: {Opcode: SET, Operand: RegisterH, Bit: 5},
	0xED: {Opcode: SET, Operand: RegisterL, Bit: 5},
	0xEE: {Opcode: SET, Operand: RegisterHLP, Bit: 5},
	0xEF: {Opcode: SET, Operand: RegisterA, Bit: 5},
	0xF0: {Opcode: SET, Operand: RegisterB, Bit: 6},
	0xF1: {Opcode: SET, Operand: RegisterC, Bit: 6},
	0xF2: {Opcode: SET, Operand: RegisterD, Bit: 6},
	0xF3: {Opcode: SET, Operand: RegisterE, Bit: 6},
	0xF4: {Opcode: SET, Operand: RegisterH, Bit: 6},
	0xF5: {Opcode: SET, Operand: RegisterL, Bit: 6},
	0xF6: {Opcode: SET, Operand: RegisterHLP, Bit: 6},
	0xF7: {Opcode: SET, Operand: RegisterA, Bit: 6},
	0xF8: {Opcode: SET, Operand: RegisterB, Bit: 7},
	0xF9: {Opcode: SET, Operand: RegisterC, Bit: 7},
	0xFA: {Opcode: SET, Operand: RegisterD, Bit: 7},
	0xFB: {Opcode: SET, Operand: RegisterE, Bit: 7},
	0xFC: {Opcode: SET, Operand: RegisterH, Bit: 7},
	0xFD: {Opcode: SET, Operand: RegisterL, Bit: 7},
	0xFE: {Opcode: SET, Operand: RegisterHLP, Bit: 7},
	0xFF: {Opcode: SET, Operand: RegisterA, Bit: 7},
}

func TestPrefixInstruction(t *testing.T) {
	for op := range 0xFF + 1 {
		expected := allPrefixInstructions[uint8(op)]
		got := DecodePrefixInstruction(uint8(op))
		if got != expected {
			t.Errorf("For opcode %#x, expected prefix instruction %v, got prefix instruction %v", op, expected, got)
		}
	}
}
