// Code generated by "stringer -type=Register"; DO NOT EDIT.

package decode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegisterNone-0]
	_ = x[RegisterA-1]
	_ = x[RegisterB-2]
	_ = x[RegisterC-3]
	_ = x[RegisterD-4]
	_ = x[RegisterE-5]
	_ = x[RegisterH-6]
	_ = x[RegisterL-7]
	_ = x[RegisterHLP-8]
}

const _Register_name = "RegisterNoneRegisterARegisterBRegisterCRegisterDRegisterERegisterHRegisterLRegisterHLP"

var _Register_index = [...]uint8{0, 12, 21, 30, 39, 48, 57, 66, 75, 86}

func (i Register) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Register_index)-1 {
		return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Register_name[_Register_index[idx]:_Register_index[idx+1]]
}
