// Code generated by "stringer -type=RSTVector"; DO NOT EDIT.

package decode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RST0-0]
	_ = x[RST1-8]
	_ = x[RST2-16]
	_ = x[RST3-24]
	_ = x[RST4-32]
	_ = x[RST5-40]
	_ = x[RST6-48]
	_ = x[RST7-56]
}

const (
	_RSTVector_name_0 = "RST0"
	_RSTVector_name_1 = "RST1"
	_RSTVector_name_2 = "RST2"
	_RSTVector_name_3 = "RST3"
	_RSTVector_name_4 = "RST4"
	_RSTVector_name_5 = "RST5"
	_RSTVector_name_6 = "RST6"
	_RSTVector_name_7 = "RST7"
)

func (i RSTVector) String() string {
	switch {
	case i == 0:
		return _RSTVector_name_0
	case i == 8:
		return _RSTVector_name_1
	case i == 16:
		return _RSTVector_name_2
	case i == 24:
		return _RSTVector_name_3
	case i == 32:
		return _RSTVector_name_4
	case i == 40:
		return _RSTVector_name_5
	case i == 48:
		return _RSTVector_name_6
	case i == 56:
		return _RSTVector_name_7
	default:
		return "RSTVector(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
