// Code generated by "stringer -type=WordRegister"; DO NOT EDIT.

package decode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WordRegisterNone-0]
	_ = x[WordRegisterBC-1]
	_ = x[WordRegisterDE-2]
	_ = x[WordRegisterHL-3]
	_ = x[WordRegisterAF-4]
	_ = x[WordRegisterSP-5]
}

const _WordRegister_name = "WordRegisterNoneWordRegisterBCWordRegisterDEWordRegisterHLWordRegisterAFWordRegisterSP"

var _WordRegister_index = [...]uint8{0, 16, 30, 44, 58, 72, 86}

func (i WordRegister) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WordRegister_index)-1 {
		return "WordRegister(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WordRegister_name[_WordRegister_index[idx]:_WordRegister_index[idx+1]]
}
