// Code generated by "stringer -type=InterruptVector"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterruptVectorNone-0]
	_ = x[InterruptVectorVBlank-72]
	_ = x[InterruptVectorStat-80]
	_ = x[InterruptVectorTimer-88]
	_ = x[InterruptVectorSerial-96]
	_ = x[InterruptVectorJoypad-104]
}

const (
	_InterruptVector_name_0 = "InterruptVectorNone"
	_InterruptVector_name_1 = "InterruptVectorVBlank"
	_InterruptVector_name_2 = "InterruptVectorStat"
	_InterruptVector_name_3 = "InterruptVectorTimer"
	_InterruptVector_name_4 = "InterruptVectorSerial"
	_InterruptVector_name_5 = "InterruptVectorJoypad"
)

func (i InterruptVector) String() string {
	switch {
	case i == 0:
		return _InterruptVector_name_0
	case i == 72:
		return _InterruptVector_name_1
	case i == 80:
		return _InterruptVector_name_2
	case i == 88:
		return _InterruptVector_name_3
	case i == 96:
		return _InterruptVector_name_4
	case i == 104:
		return _InterruptVector_name_5
	default:
		return "InterruptVector(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
